version: '3.8'

services:
  db:
    image: postgres:15
    container_name: provy_db
    environment:
      POSTGRES_DB: provy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: provy_app
    ports:
      - "8080:8081"
    environment:
      DB_URL: jdbc:postgresql://db:5432/provy
      DB_USER: postgres
      DB_PASSWORD: 1234
      JWT_SECRET: 0123456789ABCDEF0123456789ABCDEF
      JWT_EXPIRATION_MILLIS: 3600000
    depends_on:
      - db

volumes:
  db_data:
